name: Build

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.8', '3.12']
                node_version: ['20.0']
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Base Setup
              uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

            - name: Install Package
              run: |
                  python -m pip install --upgrade -v -e ".[examples, tests, docs]"

            - name: Run Linter
              run: |
                  yarn run lint

            - name: Run Tests
              run: |
                  yarn run test

            - name: Check Documentation
              if: ${{ matrix.os == 'ubuntu-latest' }}
              working-directory: docs
              run: |
                  sudo apt install -y pandoc
                  make html
