name: Build

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.8', '3.12']
                node-version: ['20.0']
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Base Setup
              uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
              with:
                  python_version: ${{ matrix.python-version }}
                  node_version: ${{ matrix.node-version }}

            - name: Package Setup
              run: |
                  python -m pip install -v -e .

            - name: Run Linter
              run: |
                  jlpm run lint

            - name: Run Tests
              run: |
                  jlpm run test

            - name: Check Documentation
              if: ${{ matrix.os == 'ubuntu-latest' }}
              working-directory: docs
              run: |
                  sudo apt install -y pandoc
                  make html
