name: Build

on:
    push:
        branches: main
    pull_request:
        branches: '*'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.8', '3.12']
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Base Setup
              uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
              with:
                  node_version: '20.0'

            - name: Install Dependencies
              run: |
                  python -m pip install -U codecov
                  npm install -g codecov

            - name: Run Tests
              run: |
                  python -m pip install --upgrade -v -e ".[examples, tests, docs]"
                  jlpm run test

            - name: Check Linting
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  jlpm run lint

            - name: Check Documentation
              if: ${{ matrix.os == 'ubuntu-latest' }}
              working-directory: docs
              run: |
                  sudo apt install -y pandoc
                  make html
