name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Base Setup
              uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
              with:
                  node_version: '20.0'
                  python-version: '3.12'

            - name: Build Package
              run: |
                  python -m pip install build
                  python -m build .

            - name: Store Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: python-package-distributions
                  path: dist/ipypandas*
    package:
        runs-on: ubuntu-latest
        needs:
            - build
        environment:
            name: testpypi
            url: https://test.pypi.org/p/ipypandas
        permissions:
            id-token: write
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: python-package-distributions
                  path: dist/

            - name: Publish Package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
