name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Base Setup
              uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
              with:
                  python_version: '3.12'
                  node_version: '20.0'

            - name: Package Setup
              run: |
                  python -m pip install -v -e .[all]

            - name: Build Packages
              run: |
                  python -m hatch build
                  jlpm pack -o lib/ipypandas.tar.gz

            - name: Store Python Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: python-package
                  path: dist/ipypandas*

            - name: Store NPM Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: npm-package
                  path: lib/ipypandas*
    pypi:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: testpypi
            url: https://test.pypi.org/p/ipypandas
        permissions:
            id-token: write
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: python-package
                  path: dist/

            - name: Publish Package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
    npmjs:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Registry Setup
              uses: actions/setup-node@v4
              with:
                  registry-url: 'https://registry.npmjs.org'
                  node-version: '20.0'
                  always-auth: true

            - name: Base Setup
              uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
              with:
                  python_version: '3.12'
                  node_version: '20.0'

            - name: Package Setup
              run: |
                  python -m pip install -v -e .[all]

            - name: Publish Package
              run: |
                  jlpm npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
